---
- name: Create frontend network
  community.docker.docker_network:
    name: frontend
    state: present

- name: Create backend network
  community.docker.docker_network:
    name: backend
    state: present

- name: Verify frontend network
  community.docker.docker_network_info:
    name: frontend

- name: Verify backend network
  community.docker.docker_network_info:
    name: backend
